apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-database-backup-monthly
  namespace: db-backup
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-database-backup
            image: iamjanam/mysql-backup-to-s3:v1 
            imagePullPolicy: Always
            env:
              - name: AWS_ACCESS_KEY_ID
                value: "your access key id"
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                   secretKeyRef:
                     name: aws-secret-access-key
                     key: aws_secret_access_key
              - name: AWS_DEFAULT_REGION
                value: "eu-central-1"
              - name: AWS_BUCKET_NAME
                value: "app-mysqldb-backup"
              - name: AWS_BUCKET_BACKUP_PATH
                value: "monthly"
              - name: TARGET_DATABASE_HOST
                value: "db-ip-or-url"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: "db name"
              - name: TARGET_DATABASE_USER
                value: "backup"
              - name: DELETE_OLDER_THAN
                value: "365 days"                 
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: target-app-database-password
                     key: database_password
              - name: SLACK_ENABLED
                value: "true"
              - name: SLACK_CHANNEL
                value: "#backup-notification channels"
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                   secretKeyRef:
                     name: slack-webhook-url
                     key: slack_webhook_url
          restartPolicy: Never
