apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-database-backup-pvc
  namespace: db-backup
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi