apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
  namespace: db-backup
type: Opaque
data:
  aws_secret_access_key: your-aws-secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: target-app-database-password
  namespace: db-backup
type: Opaque
data:
  database_password: your-db-password
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
  namespace: db-backup
type: Opaque
data:
  slack_webhook_url: your-slack-webhook